### ISSUE TITLE
色調整をしやすくする

### ISSUE THREAD

**Issue by hiyakake** [AyumuNekozuki/niconico-darkmode#13]
文字色の指定が「white」になっているなどMDのダークテーマガイドラインに沿っていない部分が結構あると思います。
明度の指定は何度も調整してバランスを確認する必要があると思いますのでCSS変数を使うか、SCSSに置き換えてはいかがでしょう？

**Comment by AyumuNekozuki** [comment]
MDのガイドラインについては、見やすさ~と制作の勢いだけで作っていた~ので、現状完全に無視している状態になります。
確認して対応します。

CSS変数やSCSSについては、現状の実装のしづらさを痛感しており、v1.2.0で予定しているダークモードのオンオフ設定の実装と同時に何かしらの形でコードを一新する予定です。
参考にさせていただきます。

**Comment by AyumuNekozuki** [comment]
以上の件、ニコニコ総合／ニコニコ動画に対応しました！
詳しくは → [Release v1.1.2](https://github.com/AyumuNekozuki/niconico-darkmode/releases/tag/v1.1.2)

**Comment by AyumuNekozuki** [comment]
動画・生放送共にSCSS化完了です！

**Comment by hiyakake** [comment]
おめでとう！
