### ISSUE TITLE
[v2.3.5]コモンズ関連の表示崩れ

### ISSUE THREAD

**Issue by Leies-202** [AyumuNekozuki/niconico-darkmode#150]
## 概要
ニコニコモンズの一部部分に表示崩れ(?)を確認したので報告します。

## 内容
1.[コモンズ作品登録画面(宣誓)](https://commons.nicovideo.jp/upload)の登録する作品の選択(サムネイル画像の登録)でファイルをアップロードしたときに出るファイル名が黒文字のままで見えない。

2.コモンズ登録作品の作品情報変更画面(https://commons.nicovideo.jp/material/edit/nc○○ )の[タイトル]と[コメント投稿]の部分の背景が白のまま。

## 参考画像(Twitter)

https://twitter.com/CMDR_Leies/status/1424675128336478215

## 環境
Microsoft Edge バージョン 92.0.902.67 (公式ビルド) (64 ビット)

## From
@CMDR_Leies

**Comment by AyumuNekozuki** [comment]
修正しました！
