### ISSUE TITLE
[2.4.1] お知らせからバッジ一覧に飛ぶとダークモード化されない

### ISSUE THREAD

**Issue by momoirodouhu** [AyumuNekozuki/niconico-darkmode#227]
## 内容
お知らせ一覧のバッジ獲得のお知らせからバッジ一覧に飛ぶとバッジ一覧の部分がダークモード化されない
その後適応し直すとしっかりダークモード化される
## 画像
![image](https://user-images.githubusercontent.com/66015725/157845886-0e29a81e-56d5-4a8d-8eb7-6d40e2fd8db1.png)
## URL
https://www.nicovideo.jp/my/badge?from=oshirase_pc&_topic=yzwt_badge_give
## 環境
FireFox

**Comment by AyumuNekozuki** [comment]
TODO: どういう条件で発生するのか条件切り分けをする
