### ISSUE TITLE
[2.4.1] ニコ生で「次回の放送をリクエストしませんか」という表示がダークモード化されない

### ISSUE THREAD

**Issue by momoirodouhu** [AyumuNekozuki/niconico-darkmode#231]
## 詳細
放送リクエストの上に表示される吹き出しがダークモードに対応していません
表示される条件はそのブラウザで一度も押していないときだと思います(未検証)
## 画像
![image](https://user-images.githubusercontent.com/66015725/158567389-f6c906f9-b563-42e4-aa9f-e3f8c2d11c4b.png)
## URL
https://live.nicovideo.jp/watch/lvXXXXXXXXX
## 環境
FireFox

**Comment by AyumuNekozuki** [comment]
バルーン系使いまわされること多いから、できれば記述まとめたい感ある

**Comment by AyumuNekozuki** [comment]
対応済み
