### ISSUE TITLE
[2.4.1] コメント投稿時に出る活動ガイドラインのダイアログがダークモードにならない

### ISSUE THREAD

**Issue by momoirodouhu** [AyumuNekozuki/niconico-darkmode#233]
## 詳細
コメントを投稿する際に出てくるニコニコ活動ガイドラインに沿ったコメントを投稿しましょうというダイアログがダークモード化されていません
このダイアログが出てくるタイミングはわからないです すみません
対応お願いいたします
## 画像
![image](https://user-images.githubusercontent.com/66015725/159174641-3c7383ca-09ac-430f-8e05-f2d6d6613069.png)
## 環境
FireFox

**Comment by AyumuNekozuki** [comment]
Cookie消した時とかに高確率で出そう
