### ISSUE TITLE
投稿者用ページが適用されない

### ISSUE THREAD

**Issue by AlphaNull16299** [AyumuNekozuki/niconico-darkmode#25]
投稿者用ページが反映されていないので、反映されるようにしてほしい。
投稿するときに明るくて目が逝きます。

**Comment by AyumuNekozuki** [comment]
issue ありがとうございます！
現時点ではまだ未対応の状態です。
ガレージ周り（特に概要欄入力のところ）は、下手にいじると投稿者が意図しているデザインとは離れてしまったりするため、慎重に実装させていただいています。

今年中には対応しますので、気長にお待ちいただければ...！

**Comment by AlphaNull16299** [comment]
わかりました！平日なのにご返答ありがとうございます！

**Comment by AyumuNekozuki** [comment]
大変おまたせ致しました！
本日リリースの v2.0.0 にてガレージ（投稿動画一覧／シリーズ／アナリティクス）に対応しました！

詳しくはリリースをご覧ください。
https://github.com/AyumuNekozuki/niconico-darkmode/releases/tag/v2.0.0
