### ISSUE TITLE
[v2.2.0] マイページの縦三点リーダーが反応しない

### ISSUE THREAD

**Issue by AyumuNekozuki** [AyumuNekozuki/niconico-darkmode#250]
## 内容 
マイページでのマイリストや履歴に存在する各動画の縦三点リーダーが左クリックをしてもマイリストに登録や履歴から削除などの項目が出ない
ニコレポの縦三点リーダーは正常です
 
## 問題が発生したURL 
https://www.nicovideo.jp/user/17793726/video?ref=pc_userpage_menu
 
## 環境 
Chrome
 
## From 
@takes001 from GForm

**Comment by momoirodouhu** [comment]
メニューに直接ついているposition:absoluteの基準点が原因っぽいです
有効化中
![スクリーンショット 2022-08-07 174938](https://user-images.githubusercontent.com/66015725/183283118-5537ef5e-185d-4f03-ba26-2112e50c913d.png)
無効化中
![スクリーンショット 2022-08-07 175018](https://user-images.githubusercontent.com/66015725/183283119-4355c897-598c-4e6f-9a7d-aced0be2b1e6.png)

NC-MediaObject-action についている filter: invert(100%) を無効化すると白くなりますが場所は正しくなります
https://github.com/AyumuNekozuki/niconico-darkmode/blob/9b9a9121b3242e1704d9ab4f02edd022b12ee881/src/style_for/video/mypage/_mypage-card.scss#L236

**Comment by momoirodouhu** [comment]
軽く調べた感じcssの謎仕様っぽいです
対応としては子のメニュー(NC-ThreePointMenu-menu)にフィルタを移す感じだと思います

**Comment by AyumuNekozuki** [comment]
対応ありがとうございます！（めちゃくちゃ助かる）
filterにそんなあれがあったとは...
もらったPR、ちょっと今手が込んでるので後々確認します 🙏🏻

**Comment by AyumuNekozuki** [comment]
対応完了しました #272
