### ISSUE TITLE
[v2.6.4] マイリストアイテムがダークモード化されない

### ISSUE THREAD

**Issue by momoirodouhu** [AyumuNekozuki/niconico-darkmode#263]
# 詳細
マイページ/ユーザーページ上のマイリストアイテムがダークモード化されない

## URL 
[自分のマイリスト](https://www.nicovideo.jp/my/mylist?ref=pc_mypage_menu) [フォロー中のマイリスト](https://www.nicovideo.jp/my/follow/mylist) 
## 環境
FireFox 103
## 参考画像
![image](https://user-images.githubusercontent.com/66015725/185431652-ef524109-5363-4b43-bc82-4ba0ed70002b.png)

**Comment by AyumuNekozuki** [comment]
対応完了しました #272
