### ISSUE TITLE
[2.4.6] commonHeader ユーザータブリニューアルによる表示崩れ

### ISSUE THREAD

**Issue by momoirodouhu** [AyumuNekozuki/niconico-darkmode#268]
# 内容
クリエイターサポート機能追加によってヘッダー部のその他タブとユーザーメニューがダークモードから外れてます
## 参考
[クリエイターサポートのインフォ](http://blog.nicovideo.jp/niconews/175014.html)

**Comment by AyumuNekozuki** [comment]
対応完了しました #272
