### ISSUE TITLE
[v2.4.7] フォロー中の番組内の文字が見えない

### ISSUE THREAD

**Issue by momoirodouhu** [AyumuNekozuki/niconico-darkmode#296]
# 詳細
[生放送トップ](https://live.nicovideo.jp/)の上部にある[フォロー中の番組]一覧のタイトルや放送者名が見えなくなっています
## 画像
![image](https://user-images.githubusercontent.com/66015725/197338874-83722ae4-38bc-4d5d-a99f-ce0aa3430c52.png)
## 環境
Firefox 106

**Comment by momoirodouhu** [comment]
## 追記
トップページでは上記のようになりますが放送ページでは適用すらされないようです
issueを分けたほうがいいでしょうかね?
## 画像
<img src="https://user-images.githubusercontent.com/66015725/197338970-90abe351-6304-4403-9e42-e3bc9ea8d782.png" width="600px">

**Comment by AyumuNekozuki** [comment]
issueわけなくて大丈夫ですー
ありがとうございます！

**Comment by AyumuNekozuki** [comment]
こちら v2.4.8 でfixしましたー
