### ISSUE TITLE
【開発環境】gulpのwatchが動かない

### ISSUE THREAD

**Issue by AyumuNekozuki** [AyumuNekozuki/niconico-darkmode#54]
gulpのwatchが動いていない気がする

## 状況
* `watch` が終わらない
* `src`内ファイル編集・保存時に、`dest`内のファイルが更新されない

※ docker-composeを終了、再起動させると再度動作し、生成されるが、'watch'のみ動作しない

(windows / wsl2 / ubuntu)
![image](https://user-images.githubusercontent.com/47974873/101313495-940d8d80-3899-11eb-9edb-10c7fc300f77.png)

別環境(mac / vagrant / ubuntu )でも発生
<img width="604" alt="スクリーンショット 2020-12-07 14 39 59" src="https://user-images.githubusercontent.com/47974873/101313732-2e6dd100-389a-11eb-833c-8d4d1c888e96.png">

## 該当箇所
`etc/compile/gulpfile.js`

```js etc/compile/gulpfile.js

/**変更の追跡 */
function watch() {
	gulp.watch(['src/style_for/**/*.scss'], styles);
	gulp.watch(['src/**/*.php', 'src/**/*.html'], php);
	gulp.watch(['src/images/**/*'], images);
	gulp.watch(['src/js/**/*.js'], js);
	gulp.watch(['src/**/*.json'], json);
}

```

**Comment by hiyakake** [comment]
時間あるときに見てみます

**Comment by hiyakake** [comment]
`Starting Watch` は変更の追跡を開始するという意味なので正常なメッセージです。

mac / vagrant / ubuntuですが、Dockerはそもそも仮想マシン上で動かすものではなくホストOSで動かすものなので使い方が間違っています。
Macで動かす場合はDocker for MacをホストOSにインストールしてください。
WSL2についてもDockerのインストール方法によってはファイルのbindがうまく行かないのでそのせいかもしれません。

一旦仕様チェックしてみます。

**Comment by AyumuNekozuki** [comment]
なるほど...
再セットアップして再度やってみます！

**Comment by AyumuNekozuki** [comment]
ありがとうございます！（Slackでも書きましたが）

## Mac環境
* vagrant環境上にdockerを入れてしまっていた
* docker for Mac にて再セットアップ
* 無事更新できた！

## Windows環境
* 元から docker for Windows にてセットアップ済み
* 色々いじったが結果変わらず
* Macで動いたので、個人の環境下 or Windows or WSL2 が原因の可能性

**Comment by hiyakake** [comment]
WindowsのほうがWindowsとDockerが最新か確かめてください。

**Comment by AyumuNekozuki** [comment]
Windowsのほう確認してきました。

* Windows 10 Pro v1909
* Docker version 19.03.13（最新版）
* docker-compose version 1.27.4（最新版）

Windowsは1909で止めてます。
理由は、最新版のWindows Updateが自環境に来ないのと、手動アプデをした際にWindowsが強制終了するようになり、1909に戻した為です。

dockerはどちらも最新版を使ってます。

**Comment by AyumuNekozuki** [comment]
@tearaikazuki 
作業枠での件、進捗あったので一応確認して頂けると！

## 猫月環境での結果
### Mac 
1. vagrant上に dockerを入れてしまっていたので、docker for Macでセットアップし直し
2. 無事更新できた！

### Windows
1. 元から docker for Windowsでセットアップ済み
2. 色々いじったが結果変わらず
3. Macで動いたので、個人の環境下 or Windows or WSL2 が原因の可能性

* Windows と WSLのディレクトリシステムの違い？
* Dockerは仕組み上、前提環境が整ってさえすればホストOSがなんであろうと同じように動くはず

**Comment by AyumuNekozuki** [comment]
Windowsも無事できたのでご報告です！！

* docker for Windows
* WSLを通さず cmdで実行
* コードを以下のように変更

```
/**変更の追跡 */
function watch() {
	gulp.watch(['src/style_for/**/*.scss'],{ usePolling: true }, styles);
	gulp.watch(['src/**/*.php', 'src/**/*.html'],{ usePolling: true }, php);
	gulp.watch(['src/images/**/*'],{ usePolling: true }, images);
	gulp.watch(['src/js/**/*.js'],{ usePolling: true }, js);
	gulp.watch(['src/**/*.json'],{ usePolling: true }, json);
}
```
* ディレクトリとか全くいじらなくてOK
![image](https://user-images.githubusercontent.com/47974873/101345955-2c703600-38cb-11eb-9128-fdad10cc4afb.png)
