### ISSUE TITLE
マイリストから作成を暗くしてください

### ISSUE THREAD

**Issue by AyumuNekozuki** [AyumuNekozuki/niconico-darkmode#70]
## 内容 
ニコ動のシリーズのページの右側にある[マイリストから作成]のところが周りが黒いのに明るい水色で少し見づらいです。濃い青等に変更していただきたいです
 
## 問題が発生したURL 
https://www.upload.nicovideo.jp/garage/series
 
## 環境 
Firefox
 
## From 
@momoirodouhufrom GForm

**Comment by momoirodouhu** [comment]
バージョン2.0.1です 書き忘れてました

**Comment by AyumuNekozuki** [comment]
確認しました！次バージョンで修正入れます！

**Comment by AyumuNekozuki** [comment]
対応済み（たぶん）
