### ISSUE TITLE
Dev Consoleに表示されるバージョンが一つ前のものになっている

### ISSUE THREAD

**Issue by tearaikazuki** [AyumuNekozuki/niconico-darkmode#84]
# 内容

![スクリーンショット 2021-03-24 4 46 09](https://user-images.githubusercontent.com/19515213/112208792-190b8f80-8c5c-11eb-8a3e-a1ac2d0d84ed.png)

##環境
- Chrome [89.0.4389.90]
- niconico Darkmode [2.0.2]

**Comment by AyumuNekozuki** [comment]
対応漏れました🙏
