### ISSUE TITLE
バッジページのダークモードが解除されない

### ISSUE THREAD

**Issue by hikaru-soeda** [AyumuNekozuki/niconico-darkmode#91]
## 内容
ヘッダー→設定→ダークモード：オフ
マイページ→バッジ
バッジの一覧部分がダークモードのままになっています。

## 問題が発生したURL
https://www.nicovideo.jp/my/badge

## 環境
- niconico Darkmode 2.0.3
- Microsoft Edge 89.0.774.68 
- Google Chrome 89.0.4389.114

**Comment by AyumuNekozuki** [comment]
ご報告ありがとうございます！次バージョンで修正予定です。
